daisy_rani_kesavan/week_05/day02/Oceans/config/routes.rb
Rails.application.routes.draw do
  resources :oceans

end

daisy_rani_kesavan/week_05/day02/Oceans/app/models/ocean.rb
class Ocean < ActiveRecord::Base
	validates :name, presence: true
end

daisy_rani_kesavan/week_05/day02/Oceans/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

daisy_rani_kesavan/week_05/day02/Oceans/app/controllers/oceans_controller.rb
class OceansController < ApplicationController
  before_action :set_ocean, only: [:show, :edit, :update, :destroy]

  # GET /oceans
  # GET /oceans.json
  def index
    @oceans = Ocean.all
  end

  # GET /oceans/1
  # GET /oceans/1.json
  def show
  end

  # GET /oceans/new
  def new
    @ocean = Ocean.new
  end

  # GET /oceans/1/edit
  def edit
  end

  # POST /oceans
  # POST /oceans.json
  def create
    @ocean = Ocean.new(ocean_params)

    respond_to do |format|
      if @ocean.save
        format.html { redirect_to @ocean, notice: 'Ocean was successfully created.' }
        format.json { render :show, status: :created, location: @ocean }
      else
        format.html { render :new }
        format.json { render json: @ocean.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oceans/1
  # PATCH/PUT /oceans/1.json
  def update
    respond_to do |format|
      if @ocean.update(ocean_params)
        format.html { redirect_to @ocean, notice: 'Ocean was successfully updated.' }
        format.json { render :show, status: :ok, location: @ocean }
      else
        format.html { render :edit }
        format.json { render json: @ocean.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oceans/1
  # DELETE /oceans/1.json
  def destroy
    @ocean.destroy
    respond_to do |format|
      format.html { redirect_to oceans_url, notice: 'Ocean was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ocean
      @ocean = Ocean.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocean_params
      params.require(:ocean).permit(:name, :image, :place, :area, :volume)
    end
end

daisy_rani_kesavan/week_05/day02/Oceans/app/helpers/application_helper.rb
module ApplicationHelper
end

daisy_rani_kesavan/week_05/day02/Oceans/app/helpers/oceans_helper.rb
module OceansHelper
end

daisy_rani_kesavan/week_05/day02/Oceans/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oceans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

daisy_rani_kesavan/week_05/day02/Oceans/app/views/oceans/_form.html.erb
<%= form_for(@ocean) do |f| %>
  <% if @ocean.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ocean.errors.count, "error") %> prohibited this ocean from being saved:</h2>

      <ul>
      <% @ocean.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

daisy_rani_kesavan/week_05/day02/Oceans/app/views/oceans/edit.html.erb
<h1>Editing Ocean</h1>

<%= render 'form' %>

<%= link_to 'Show', @ocean %> |
<%= link_to 'Back', oceans_path %>

daisy_rani_kesavan/week_05/day02/Oceans/app/views/oceans/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Oceans</h1>
<table class="ocean-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Place</th>
      <th>Area</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oceans.each do |ocean| %>
      <tr>
        <td><%= ocean.name %></td>
        <td><%= image_tag(ocean.image) %></td>
        <td><%= ocean.place %></td>
        <td><%= ocean.area %></td>
        <td><%= ocean.volume %></td>
        <td><%= link_to 'Show', ocean %></td>
        <td><%= link_to 'Edit', edit_ocean_path(ocean) %></td>
        <td><%= link_to 'Destroy', ocean, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ocean', new_ocean_path %>

daisy_rani_kesavan/week_05/day02/Oceans/app/views/oceans/new.html.erb
<h1>New Ocean</h1>

<%= render 'form' %>

<%= link_to 'Back', oceans_path %>

daisy_rani_kesavan/week_05/day02/Oceans/app/views/oceans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ocean.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ocean.image %>
</p>

<p>
  <strong>Place:</strong>
  <%= @ocean.place %>
</p>

<p>
  <strong>Area:</strong>
  <%= @ocean.area %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @ocean.volume %>
</p>

<%= link_to 'Edit', edit_ocean_path(@ocean) %> |
<%= link_to 'Back', oceans_path %>